// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ordering.Infrastructure;

#nullable disable

namespace Ordering.Infrastructure.Migrations
{
    [DbContext(typeof(OrderingContext))]
    [Migration("20260721084506_Test")]
    partial class Test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("DatabaseType", "mysql")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MicroserviceFramework.Auditing.Model.AuditEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("EntityId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("entity_id");

                    b.Property<string>("OperationId")
                        .HasColumnType("varchar(36)")
                        .HasColumnName("operation_id");

                    b.Property<string>("OperationType")
                        .HasMaxLength(256)
                        .HasColumnType("varchar")
                        .HasColumnName("operation_type");

                    b.Property<string>("Type")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.HasIndex("OperationId");

                    b.ToTable("ordering_audit_entity");
                });

            modelBuilder.Entity("MicroserviceFramework.Auditing.Model.AuditOperation", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<float?>("Accuracy")
                        .HasColumnType("float")
                        .HasColumnName("accuracy");

                    b.Property<float?>("Altitude")
                        .HasColumnType("float")
                        .HasColumnName("altitude");

                    b.Property<int?>("Battery")
                        .HasColumnType("int")
                        .HasColumnName("battery");

                    b.Property<float?>("Bearing")
                        .HasColumnType("float")
                        .HasColumnName("bearing");

                    b.Property<long?>("CreationTime")
                        .HasColumnType("bigint")
                        .HasColumnName("creation_time");

                    b.Property<string>("CreatorId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("creator_id");

                    b.Property<string>("CreatorName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("creator_name");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("device_id");

                    b.Property<string>("DeviceModel")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("device_model");

                    b.Property<int>("Elapsed")
                        .HasColumnType("int")
                        .HasColumnName("elapsed");

                    b.Property<bool?>("Emulator")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("emulator");

                    b.Property<long>("EndTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("end_time");

                    b.Property<string>("IMEI")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("imei");

                    b.Property<string>("IP")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("ip");

                    b.Property<decimal?>("Lat")
                        .HasPrecision(11, 8)
                        .HasColumnType("decimal(11,8)")
                        .HasColumnName("lat");

                    b.Property<decimal?>("Lng")
                        .HasPrecision(11, 8)
                        .HasColumnType("decimal(11,8)")
                        .HasColumnName("lng");

                    b.Property<string>("LocationSource")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("location_source");

                    b.Property<string>("Method")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("method");

                    b.Property<string>("OSVersion")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("os_version");

                    b.Property<float?>("Orientation")
                        .HasColumnType("float")
                        .HasColumnName("orientation");

                    b.Property<string>("Path")
                        .HasColumnType("longtext")
                        .HasColumnName("path");

                    b.Property<string>("Platform")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("platform");

                    b.Property<string>("QueryString")
                        .HasColumnType("longtext")
                        .HasColumnName("query_string");

                    b.Property<string>("Screen")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("screen");

                    b.Property<int?>("Signal")
                        .HasColumnType("int")
                        .HasColumnName("signal");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("trace_id");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("EndTime");

                    b.ToTable("ordering_audit_operation");
                });

            modelBuilder.Entity("MicroserviceFramework.Auditing.Model.AuditProperty", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("EntityId")
                        .HasColumnType("varchar(36)")
                        .HasColumnName("entity_id");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("name");

                    b.Property<string>("NewValue")
                        .HasColumnType("longtext")
                        .HasColumnName("new_value");

                    b.Property<string>("OriginalValue")
                        .HasColumnType("longtext")
                        .HasColumnName("original_value");

                    b.Property<string>("Type")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.ToTable("ordering_audit_property");
                });

            modelBuilder.Entity("Ordering.Domain.AggregateRoots.Order.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<string>("BuyerId")
                        .HasColumnType("varchar(36)")
                        .HasColumnName("buyer_id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<long?>("CreationTime")
                        .HasColumnType("bigint")
                        .HasColumnName("creation_time");

                    b.Property<string>("CreatorId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("creator_id");

                    b.Property<string>("CreatorName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("creator_name");

                    b.Property<string>("DeleterId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("deleter_id");

                    b.Property<string>("DeleterName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("deleter_name");

                    b.Property<long?>("DeletionTime")
                        .HasColumnType("bigint")
                        .HasColumnName("deletion_time");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Dict")
                        .HasColumnType("JSON")
                        .HasColumnName("dict");

                    b.Property<string>("Extra")
                        .HasColumnType("JSON")
                        .HasColumnName("extra");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<long?>("LastModificationTime")
                        .HasColumnType("bigint")
                        .HasColumnName("last_modification_time");

                    b.Property<string>("LastModifierId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("last_modifier_id");

                    b.Property<string>("LastModifierName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("last_modifier_name");

                    b.Property<string>("List")
                        .HasColumnType("JSON")
                        .HasColumnName("list");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("status");

                    b.Property<string>("TestId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar")
                        .HasColumnName("test_id");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("CreationTime");

                    b.ToTable("ordering_order");
                });

            modelBuilder.Entity("Ordering.Domain.AggregateRoots.Order.OrderItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("discount");

                    b.Property<string>("OrderId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("order_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.Property<int>("Units")
                        .HasColumnType("int")
                        .HasColumnName("units");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("ordering_order_item");
                });

            modelBuilder.Entity("Ordering.Domain.AggregateRoots.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<long?>("CreationTime")
                        .HasColumnType("bigint")
                        .HasColumnName("creation_time");

                    b.Property<string>("CreatorId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("creator_id");

                    b.Property<string>("CreatorName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("creator_name");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("name");

                    b.Property<int>("Price")
                        .HasColumnType("int")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("ordering_product");
                });

            modelBuilder.Entity("Ordering.Domain.AggregateRoots.UserInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("user", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("MicroserviceFramework.Auditing.Model.AuditEntity", b =>
                {
                    b.HasOne("MicroserviceFramework.Auditing.Model.AuditOperation", "Operation")
                        .WithMany("Entities")
                        .HasForeignKey("OperationId");

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("MicroserviceFramework.Auditing.Model.AuditProperty", b =>
                {
                    b.HasOne("MicroserviceFramework.Auditing.Model.AuditEntity", "Entity")
                        .WithMany("Properties")
                        .HasForeignKey("EntityId");

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("Ordering.Domain.AggregateRoots.Order.Order", b =>
                {
                    b.HasOne("Ordering.Domain.AggregateRoots.UserInfo", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId");

                    b.OwnsOne("Ordering.Domain.AggregateRoots.Order.Address", "Address", b1 =>
                        {
                            b1.Property<string>("OrderId")
                                .HasColumnType("varchar(255)")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("address_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("address_country");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("address_state");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("address_street");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("address_zip_code");

                            b1.HasKey("OrderId");

                            b1.ToTable("ordering_order");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("Address");

                    b.Navigation("Buyer");
                });

            modelBuilder.Entity("Ordering.Domain.AggregateRoots.Order.OrderItem", b =>
                {
                    b.HasOne("Ordering.Domain.AggregateRoots.Order.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId");

                    b.OwnsOne("Ordering.Domain.AggregateRoots.Order.Product", "Product", b1 =>
                        {
                            b1.Property<string>("OrderItemId")
                                .HasColumnType("varchar(36)")
                                .HasColumnName("id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("varchar(255)")
                                .HasColumnName("product_name");

                            b1.Property<string>("PictureUrl")
                                .HasMaxLength(300)
                                .HasColumnType("varchar(300)")
                                .HasColumnName("product_picture_url");

                            b1.Property<string>("ProductId")
                                .IsRequired()
                                .HasMaxLength(36)
                                .HasColumnType("varchar(36)")
                                .HasColumnName("product_id");

                            b1.HasKey("OrderItemId");

                            b1.HasIndex("ProductId");

                            b1.ToTable("ordering_order_item");

                            b1.WithOwner()
                                .HasForeignKey("OrderItemId");
                        });

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MicroserviceFramework.Auditing.Model.AuditEntity", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("MicroserviceFramework.Auditing.Model.AuditOperation", b =>
                {
                    b.Navigation("Entities");
                });

            modelBuilder.Entity("Ordering.Domain.AggregateRoots.Order.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
