image: docker:latest

variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  API_IMAGE: $DOCKER_REGISTRY/api:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  API_LATEST_IMAGE: $DOCKER_REGISTRY/api:$CI_COMMIT_REF_SLUG
  API_RELEASE_IMAGE: $DOCKER_REGISTRY/api:$CI_COMMIT_SHORT_SHA
  API_RELEASE_LATEST_IMAGE: $DOCKER_REGISTRY/api


before_script:
  - echo $API_IMAGE
  - docker login -u $CI_REGISTRY_USER -p $CI_TOKEN $CI_REGISTRY

stages:
  - build
  # - test
  - staging
  - publish

build:
  stage: build
  script:
    - docker build -f Dockerfile --target build --pull  .

# api-test:
#   stage: test
#   only:
#     - staging
#     - master
#     - /^release-.*$/
#   script:
#     - docker build --pull -f Dockerfile --target api-test .

staging:
  only:
    - staging
  stage: staging
  script:
    - docker build -f Dockerfile --pull --target bch-api -t $API_IMAGE .
    - docker tag $API_IMAGE $API_LATEST_IMAGE
    - docker push $API_IMAGE
    - docker push $API_LATEST_IMAGE

publish:
  only:
    - /^release-.*$/      # tag 分支 commit 之后触发
    - triggers  # API 触发
    - schedules # 每日构建触发
  stage: publish
  script:
    - docker build -f Dockerfile --pull --target bch-api -t $API_RELEASE_IMAGE .
    - docker tag $API_RELEASE_IMAGE $API_RELEASE_LATEST_IMAGE
    - docker push $API_RELEASE_IMAGE
    - docker push $API_RELEASE_LATEST_IMAGE


