using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace MicroserviceFramework.Ef.Analyzers;

[Generator(LanguageNames.CSharp)]
public class RepositoryGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 通过 CompilationProvider 构建增量管线：仅在编译变化时重新计算模型，
        // 生成代码不含时间戳，保证构建结果确定性
        var provider = context.CompilationProvider.Select(static (compilation, _) => compilation);
        context.RegisterSourceOutput(provider, static (context, compilation) =>
        {
            if (compilation == null)
            {
                return;
            }

            // 精确匹配程序集名（不包含扩展名），避免 Contains 子串误匹配
            var domainAssemblyName = Extensions.ReplaceNamespaceSegment(
                compilation.AssemblyName ?? string.Empty, "Infrastructure", "Domain");
            if (string.IsNullOrEmpty(domainAssemblyName))
            {
                return;
            }

            var domainAssemblySymbol = compilation.SourceModule.ReferencedAssemblySymbols
                .FirstOrDefault(x => x.Name == domainAssemblyName);
            if (domainAssemblySymbol == null)
            {
                return;
            }

            var list = new HashSet<string>();
            list = LoadAllTypes(domainAssemblySymbol.GlobalNamespace);

            foreach (var entity in list)
            {
                var aggregateRootInfo = compilation.GetAggregateRootInfo(entity);
                if (!aggregateRootInfo.IsAggregateRoot)
                {
                    continue;
                }

                var typeInfo = aggregateRootInfo.Type.GetTypeInfo();
                var namespaceName = Extensions.ReplaceNamespaceSegment(typeInfo.Namespace, "Domain", "Infrastructure");
                // Key 为空表示实现非泛型 IAggregateRoot 的聚合根（复合主键多属性实体），生成无键仓储
                var baseType = string.IsNullOrEmpty(aggregateRootInfo.Key)
                    ? $"EfRepository<E>"
                    : $"EfRepository<E, {aggregateRootInfo.Key}>";
                var script = $$"""
                               // <auto-generated />
                               using MicroserviceFramework.Ef;
                               using MicroserviceFramework.Ef.Repositories;
                               using {{typeInfo.Namespace}};
                               using E = {{entity}};

                               namespace {{namespaceName}};

                               public partial class {{typeInfo.TypeName}}Repository
                                   : {{baseType}}, I{{typeInfo.TypeName}}Repository
                               {
                                   public {{typeInfo.TypeName}}Repository(DbContextFactory context) : base(context)
                                   {
                                       UseQuerySplittingBehavior = true;
                                   }
                               }
                               """;

                context.AddSource($"{typeInfo.Namespace}.{typeInfo.TypeName}.g.cs",
                    SourceText.From(script, Encoding.UTF8));
            }
        });
    }

    /// <summary>
    /// 递归收集命名空间下所有类型成员的完整名称
    /// </summary>
    /// <param name="namespaceSymbol">命名空间符号</param>
    /// <returns>类型完整名称集合</returns>
    private static HashSet<string> LoadAllTypes(INamespaceSymbol namespaceSymbol)
    {
        var list = new HashSet<string>();
        foreach (var namespaceMember in namespaceSymbol
                     .GetNamespaceMembers())
        {
            var tmp = LoadAllTypes(namespaceMember);
            foreach (var item in tmp)
            {
                list.Add(item);
            }
        }

        foreach (var member in namespaceSymbol.GetMembers())
        {
            list.Add(member.ToDisplayString());
        }

        return list;
    }
}
