using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace MicroserviceFramework.Analyzers;

[Generator(LanguageNames.CSharp)]
public class RepositoryInterfaceGenerator : IIncrementalGenerator
{
    private static readonly string AggregateRootInterface
        = "MicroserviceFramework.Domain.IAggregateRoot<";

    private static readonly string NonGenericAggregateRootInterface
        = "MicroserviceFramework.Domain.IAggregateRoot";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var pipeline = context.SyntaxProvider.CreateSyntaxProvider(
            static (syntaxNode, _) => syntaxNode.IsKind(SyntaxKind.ClassDeclaration),
            static (context, cancellationToken) =>
            {
                var classDeclarationSyntax = (ClassDeclarationSyntax)context.Node;
                var assemblyClassTypeSymbol =
                    context.SemanticModel.GetDeclaredSymbol(classDeclarationSyntax, cancellationToken);

                if (assemblyClassTypeSymbol == null)
                {
                    return null;
                }

                var key = ExtractKey(assemblyClassTypeSymbol);
                if (key == null)
                {
                    return null;
                }

                return new Model(
                    assemblyClassTypeSymbol.ContainingNamespace?.ToDisplayString(
                        SymbolDisplayFormat.FullyQualifiedFormat.WithGlobalNamespaceStyle(
                            SymbolDisplayGlobalNamespaceStyle.Omitted)),
                    assemblyClassTypeSymbol.Name, key);
            });

        context.RegisterSourceOutput(pipeline, static (context, model) =>
        {
            if (model == null)
            {
                return;
            }

            var repoNamespace = model.Namespace.Replace("AggregateRoots", "Repositories");
            // Key 为空表示实现非泛型 IAggregateRoot 的聚合根（复合主键多属性实体），生成无键仓储接口
            var baseInterfaces = string.IsNullOrEmpty(model.Key)
                ? $"IRepository<E>"
                : $"IRepository<E, {model.Key}>";
            var sourceText = SourceText.From($$"""
                                               // <auto-generated time='{{DateTimeOffset.UtcNow:yyyy-MM-dd HH:mm:ss}}' />
                                               using MicroserviceFramework.Domain;
                                               using MicroserviceFramework.Extensions.DependencyInjection;
                                               using E = {{model.Namespace}}.{{model.ClassName}};

                                               namespace {{repoNamespace}};

                                               public partial interface I{{model.ClassName}}Repository
                                                   : {{baseInterfaces}}, IScopeDependency
                                               {
                                               }
                                               """, Encoding.UTF8);

            context.AddSource($"{repoNamespace}.{model.ClassName}.g.cs", sourceText);
        });
    }

    /// <summary>
    /// 从类型实现的接口中提取聚合根键类型名。
    /// 优先匹配泛型 <see cref="IAggregateRoot{TKey}"/>（返回键类型名）；
    /// 若仅实现非泛型 <see cref="IAggregateRoot"/>（复合主键多属性实体），返回空字符串表示无键；
    /// 两者均未实现返回 null（忽略该类型）。
    /// </summary>
    /// <param name="typeSymbol">待检查的类型符号</param>
    /// <returns>键类型名；空字符串表示无键聚合根；null 表示非聚合根</returns>
    private static string ExtractKey(ITypeSymbol typeSymbol)
    {
        var hasGenericAggregateRoot = false;
        string key = null;
        foreach (var @interface in typeSymbol.AllInterfaces)
        {
            var interfaceName = @interface.ToDisplayString();
            if (!interfaceName.StartsWith(AggregateRootInterface))
            {
                continue;
            }

            hasGenericAggregateRoot = true;
            key = interfaceName.Substring(
                AggregateRootInterface.Length,
                interfaceName.Length - AggregateRootInterface.Length - 1);
            break;
        }

        if (hasGenericAggregateRoot)
        {
            return key;
        }

        // 泛型接口未命中时，检查是否实现非泛型 IAggregateRoot（复合主键多属性实体）
        foreach (var @interface in typeSymbol.AllInterfaces)
        {
            if (@interface.ToDisplayString() == NonGenericAggregateRootInterface)
            {
                return string.Empty;
            }
        }

        return null;
    }

    private class Model(string @namespace, string className, string key)
    {
        public string Namespace { get; set; } = @namespace;
        public string ClassName { get; set; } = className;

        public string Key { get; set; } = key;
    }
}
